#!/usr/bin/env bash

# setup your shell by running '. ./setenv.sh' on the cli prompt
echo JAVA_HOME: $JAVA_HOME
echo HOME: $HOME

export  ROXY_HOME=$(pwd)
export  ROXY_BASE_REGION="us-east-1"
export  ROXY_BASE_AMI="ami-e9dd8596"
export  ROXY_BASE_EC2SG="sg-5098021b"
export  ROXY_BASE_ELBSG="sg-2a533661"
export  ROXY_BASE_DBSG="sg-e6e478ad"
export  ROXY_BASE_KEYPAIR="roxyKeyPair"
export  ROXY_BASE_INSTANCE_TYPE="t2.micro"
export  ROXY_BASE_VPC_CIDR="10.0.0.0/16"
export  ROXY_BASE_SUBNET1_CIDR="10.0.1.0/24"
export  ROXY_BASE_SUBNET2_CIDR="10.0.2.0/24"
export  ROXY_BASE_SUBNET3_CIDR="10.0.3.0/24"
export  ROXY_BASE_SUBNET4_CIDR="10.0.4.0/24"

echo ROXY_HOME: $ROXY_HOME
echo ROXY_BASE_REGION: $ROXY_BASE_REGION
echo ROXY_BASE_AMI: $ROXY_BASE_AMI
echo ROXY_BASE_EC2SG: $ROXY_BASE_EC2SG
echo ROXY_BASE_ELBSG: $ROXY_BASE_ELBSG
echo ROXY_BASE_DBSG: $ROXY_BASE_DBSG
echo ROXY_BASE_KEYPAIR: $ROXY_BASE_KEYPAIR
echo ROXY_BASE_INSTANCE_TYPE: $ROXY_BASE_INSTANCE_TYPE
echo  ROXY_BASE_VPC_CIDR: $ROXY_BASE_VPC_CIDR
echo  ROXY_BASE_SUBNET1_CIDR: $ROXY_BASE_SUBNET1_CIDR
echo  ROXY_BASE_SUBNET2_CIDR: $ROXY_BASE_SUBNET2_CIDR
echo  ROXY_BASE_SUBNET3_CIDR: $ROXY_BASE_SUBNET3_CIDR
echo  ROXY_BASE_SUBNET4_CIDR: $ROXY_BASE_SUBNET4_CIDR
